# Use the README file as a reference to customize settings.

Event:
  fields:
    default: title, description, price, start_time, end_time, establishment
    form: title, description, price, start_time, end_time, establishment
  relationships: establishment
  application: Application
