# Use the README file as a reference to customize settings.

Special:
  fields:
    default: title, description, start_time, end_time, establishment
    form: title, description, start_time, end_time, all_day_event, recurring, establishment
    options:
        selectors: recurring
  relationships: establishment
  application: Application
